[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "buildozer>=1.5.0",
    "kivy>=2.3.1",
    "pyperclip>=1.9.0",
    "streamlit>=1.47.1",
]
